# Generated by Django 6.0.5 on 2026-06-11 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresaparceira_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoStatusSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('PENDENTE', 'Com Pendências')], max_length=20)),
                ('status_novo', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('PENDENTE', 'Com Pendências')], max_length=20)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_status_solicitacao', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='core.solicitacaoestagio')),
            ],
            options={
                'ordering': ['-data_alteracao', '-id'],
            },
        ),
    ]
