# Generated by Django 6.0.5 on 2026-06-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historicostatussolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoestagio',
            name='justificativa_recusa',
            field=models.TextField(blank=True),
        ),
    ]
