# Generated by Django 6.0.5 on 2026-06-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_solicitacaoestagio_justificativa_recusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='curso',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='estudante',
            name='elegivel_estagio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
