# Generated by Django 6.0.5 on 2026-06-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pendencia_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoestagio',
            name='carga_horaria',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitacaoestagio',
            name='duracao_contrato',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitacaoestagio',
            name='seguro_obrigatorio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacaoestagio',
            name='supervisor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
