# Generated by Django 6.0.5 on 2026-06-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solicitacaoestagio_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaparceira',
            name='supervisor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
